language: ruby
rvm:
- 2.4.1
dist: trusty
branches:
  only:
  - master
sudo: false
addons:
  postgresql: '9.6'
  apt:
    packages:
    - libxslt1-dev
    - libxml2-dev
cache:
  - apt
  - bundler
before_script:
  - bundle exec rake travis:before_script
